language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
env:
  - CXX=clang++ CC=clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libstdc++-4.8-dev
